### ISSUE TITLE
Diagrama de casos de uso del Sistema

### ISSUE THREAD

**Issue by ainhoasolerr** [UrkoAlliBarrrena/Software-de-gesti-n-cl-nica#1]
**CONTENIDOS:**
- Actores
- Casos de uso
- Relaciones

**Comment by UrkoAlliBarrena** [comment]
Voy a crear la carpeta con los ficheros del ejercicio 1.

**Comment by ainhoasolerr** [comment]
Estoy borrando las carpetas que no sirven

**Comment by UrkoAlliBarrena** [comment]
Vale, yo ya he subido el fichero a la carpeta.

**Comment by UrkoAlliBarrena** [comment]
Cierro esta issue que ya está acabada.
