### ISSUE TITLE
Catálogo de requisitos funcionales de la aplicación

### ISSUE THREAD

**Issue by ainhoasolerr** [UrkoAlliBarrrena/Software-de-gesti-n-cl-nica#2]
**CONTENIDOS:**
- Identificador único
-  Descripción de la funcionalidad
- Importancia del requisito para el cliente
- Prioridad del requisito para la dirección del proyecto

**Comment by UrkoAlliBarrena** [comment]
Ya he creado y he subido los ficheros correspondientes.

**Comment by UrkoAlliBarrena** [comment]
La referencia que está bien es la mía. La tuya aparece vacía.

**Comment by UrkoAlliBarrena** [comment]
Cierro esta issue que ya está acabada.
