### ISSUE TITLE
Especificación de los actores del Sistema

### ISSUE THREAD

**Issue by ainhoasolerr** [UrkoAlliBarrrena/Software-de-gesti-n-cl-nica#3]
**CONTENIDOS:**
- Tipos de usuario
- Sistemas con los que interactúa
- Descripción  de la funcionalidad de los actores

**Comment by UrkoAlliBarrena** [comment]
Ya he creado los actores y sus funciones. El archivo esta subido, mirar que tal os parece.

**Comment by UrkoAlliBarrena** [comment]
Si hay que cambiar algo me decís.

**Comment by UrkoAlliBarrena** [comment]
Cierro esta issue que ya está acabada.
