### ISSUE TITLE
Especificación formal de los casos de uso 

### ISSUE THREAD

**Issue by ainhoasolerr** [UrkoAlliBarrrena/Software-de-gesti-n-cl-nica#4]
**CONTENIDO:**
- Descripción
- Precondiciones
- Secuencia normal
- Excepciones
- Postcondiciones
- Rendimiento
- Frecuencia
- Importancia
- Urgencia
- Comentarios

**Comment by ainhoasolerr** [comment]
En el diagrama faltan algunas acciones del administrador chicos

**Comment by VictoriaGarciaLovelle** [comment]
Terminado todo el caso se usos, solo quedaría de este apartado adjuntarlo

**Comment by VictoriaGarciaLovelle** [comment]
![image](https://github.com/UrkoAlliBarrrena/Software-de-gesti-n-cl-nica/assets/127880264/90df54d4-8b33-4370-be0b-28e5a008acc0)

**Comment by VictoriaGarciaLovelle** [comment]
La parte de elaboración ya esta toda terminada
